### ISSUE TITLE
Error when loading plugin

### ISSUE THREAD

**Issue by jsbUSMC** [supnate/rekit-plugin-redux-saga#1]
Hey @supnate thanks for all your work with rekit! I installed this plugin using yarn, `yarn add rekit-plugin-redux-saga` and ran into a couple of errors. After yarn added the package, using the rekit cli command that is on the rekit docs `rekit install-plugin rekit-plugin-redux-saga` fails due to cmd syntax error. It seems that the proper command is `rekit install rekit-plugin-redux-saga`, which *seemed* to work fine. However, when I was using Portal to create a new Feature, I got an error in the UI stating **TypeError: cannot read property 'hooks' of null**, in a small 'Operation Failed' modal. Additionally, I received this error message and stack trace in the console:

```sh
Warning: Failed to load plugin: redux-saga, TypeError: Cannot read property 'app' of undefined.
TypeError: Cannot read property 'app' of undefined
    at module.exports (C:\Users\me\anya\node_modules\rekit-plugin-redux-saga\action.js:16:24)
    at config.accept.forEach (C:\Users\me\anya\node_modules\rekit-core\core\plugin.js:88:71)
    at Array.forEach (native)
    at plugins.map (C:\Users\me\anya\node_modules\rekit-core\core\plugin.js:85:23)
    at Array.map (native)
    at loadPlugins (C:\Users\me\anya\node_modules\rekit-core\core\plugin.js:75:21)
    at getPlugins (C:\Users\me\anya\node_modules\rekit-core\core\plugin.js:15:5)
    at Object.getCommand (C:\Users\me\anya\node_modules\rekit-core\core\plugin.js:119:17)
    at Object.handleCommand (C:\Users\me\anya\node_modules\rekit-core\core\index.js:364:20)
    at execCmd (C:\Users\me\anya\node_modules\rekit-portal\middleware\index.js:63:17)
```

I'm fairly certain that I've followed the documentation to the letter, though I think the plugin installation could be improved upon a bit. Any idea why I'm receiving this error? Thanks for your help man

**Comment by supnate** [comment]
Hi @jsbUSMC , thank you very much for reporting this! It's a bug of Rekit portal that didn't load plugins properly. Now you can update your Rekit portal version to v2.0.4 to resolve it. Sorry for the inconvenience!

**Comment by loganpowell** [comment]
I've updated to portal v2.0.4 and installed the plugin by following the directions @jsbUSMC has provided above, but I'm still not seeing how to use this plugin instead of the default thunk. Might some more directions be provided in the README.md for this repo?

**Comment by supnate** [comment]
@loganpowell thanks for the feedback and suggestion. I will add more info in the readme. While the redux-saga plugin is installed by npm, you also need to config it in the rekit/plugins section in package.json(rekit install cli does this). After that, async actions will be created using sagas. The file name is just the same as thunk version, you may need to check if it was already created with sagas.
