### ISSUE TITLE
Error after installing plugin

### ISSUE THREAD

**Issue by pengux** [supnate/rekit-plugin-redux-saga#2]
Installning plugin with
```
rekit install rekit-plugin-redux-saga
```

then running

```
rekit add feature user
```

generate error:

```
Error: Can't find such file: [PATH TO PROJECT]/src/common/rootSaga.js
```

**Comment by aonoams** [comment]
use sudo rekit install rekit-plugin-redux-saga

**Comment by RabbleMonster** [comment]
Hi aonoams,

Thanks for the quick response.! I ran the command and it gave me the same error that npm start does.  

    node_modules\rekit-core\core\action.js:115
      ));
      ^

    SyntaxError: Unexpected token )
        at createScript (vm.js:56:10)
        at Object.runInThisContext (vm.js:97:10)
        at Module._compile (module.js:542:28)
        at Object.Module._extensions..js (module.js:579:10)
        at Module.load (module.js:487:32)
        at tryModuleLoad (module.js:446:12)
        at Function.Module._load (module.js:438:3)
        at Module.require (module.js:497:17)
        at require (internal/module.js:20:19)
        at Object.<anonymous> (C:\Users\John\TSS_FRONT_TEST\TSS_FRONT\node_modules\rekit- 
       core\core\index.js:50:16)
